version: '3.7'

services:
  fastcar-api:
    container_name: fastcar-api
    restart: on-failure
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: yarn start:dev
    env_file:
      - .env
    networks:
      - fastcar-api
    depends_on:
      - postgres
  
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'postgres'
    volumes:
      - pg-data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - fastcar-api
    restart: always

# CONTAINER DO SISTEMA GERENCIADOR DE BANCO DE DADOS (SGBD)
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - fastcar-api
    depends_on:
      - postgres

networks:
  fastcar-api:

volumes:
  pg-data:
